<?php

namespace GestionBundle\Repository;

/**
 * AttestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttestationRepository extends \Doctrine\ORM\EntityRepository
{
}
