<?php

namespace GestionBundle\Repository;

/**
 * PermutationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermutationRepository extends \Doctrine\ORM\EntityRepository
{
    public function PermutationSearchajax($valeur)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from GestionBundle:Permutation m where   m.classeS LIKE '$valeur%' ");
        return $dqlresult->getResult();
    }
}
