<?php

namespace EnseignantBundle\Repository;

/**
 * MoyennesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyennesRepository extends \Doctrine\ORM\EntityRepository
{
}
