<?php

namespace EnseignantBundle\Repository;

/**
 * SanctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionsRepository extends \Doctrine\ORM\EntityRepository
{
}
