<?php

namespace ForumBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyfa($sujet)
    {
        $Query=$this->getEntityManager()->createQuery("delete from ForumBundle:Commentaire c where c.sujet = :s")
            ->setParameter('s',$sujet);
        return $Query->getResult();
    }
}
