<?php

namespace ClubBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByRate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ClubBundle:Activity p ORDER BY p.vote DESC'
            )
            ->getResult();
    }
}
