<?php

namespace ClubBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindENS()
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from AppBundle:User m where m.roles = 'a:1:{i:0;s:15:\"ROLE_ENSEIGNANT\";}' ");
        return $dqlresult->getResult();
    }
    public function ClubSearchajax($valeur)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from ClubBundle:Club m where   m.nomclub LIKE '$valeur%' ");
        return $dqlresult->getResult();
    }
}
