<?php

namespace EnseignantBundle\Repository;

/**
 * BulletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulletinRepository extends \Doctrine\ORM\EntityRepository
{
/*
    public function MEleve($classe,$tr)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT 
            ( sum((coeff.valeur* moyennes.moyenne))/ sum(coeff.valeur) ) as moyG 
            from ScolariteBundle:Coeff  coeff inner join EnseignantBundle:Moyenne moyennes with coeff.matiere= moyennes.matiere
             and coeff.niveau= :niv and moyennes.trimestre= :m GROUP by moyennes.trimestre'
        )
            ->setParameters([
                'niv' => $classe,
                'm' => $tr


            ]);

       // return $results = $query->getArrayResult();
    }
*/
    public function REleve1($el,$tr)
    {
        $query = $this->getEntityManager()->createQuery(


            'select DISTINCT IDENTITY(f.classe) from EnseignantBundle:Moyenne m  inner join
              AppBundle:User f with f.id= m.eleve inner join ScolariteBundle:Classe c with f.classe =c.id 
              where f.id= :t  and m.trimestre = :l '
        )//->distinct()
        ->setParameters([
            't' => $el,
            'l' =>$tr ,

        ]);

        return $results = $query->getArrayResult();
    }

    public function REleve2($p,$tr)
    {
        $query = $this->getEntityManager()->createQuery(


            'SELECT 
            ( sum((coeff.valeur* moyennes.moyenne))/ sum(coeff.valeur) ) as moyG 
            from ScolariteBundle:Coeff  coeff inner join EnseignantBundle:Moyenne moyennes with coeff.matiere= moyennes.matiere
             and coeff.niveau = :p and moyennes.trimestre= :l GROUP by moyennes.trimestre'
        )
            ->setParameters([
                'p' => $p,
                'l' =>$tr ,

            ]);

        // ->setParameter('p', $p);

        return $results = $query->getResult();
    }


}
