absences_index:
    path:     /
    defaults: { _controller: "EnseignantBundle:Absences:index" }
    methods:  GET

absences_show:
    path:     /{id}/show
    defaults: { _controller: "EnseignantBundle:Absences:show" }
    methods:  GET

absences_new:
    path:     /new
    defaults: { _controller: "EnseignantBundle:Absences:new" }
    methods:  [GET, POST]

absences_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnseignantBundle:Absences:edit" }
    methods:  [GET, POST]

absences_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnseignantBundle:Absences:delete" }

absences_changeretat:
    path:   /{id}/changeretat
    defaults: { _controller: "EnseignantBundle:Absences:changeretat" }

absences_all:
    path:   /all/{id}
    defaults: { _controller: "EnseignantBundle:Absences:all" }

absences_absenceseleve:
    path:   /absenceseleve/{id}
    defaults: { _controller: "EnseignantBundle:Absences:absenceseleve" }

absences_ajouter:
    path:   /ajouter
    defaults: { _controller: "EnseignantBundle:Absences:ajouter" }

absences_modifier:
    path:   /modifier
    defaults: { _controller: "EnseignantBundle:Absences:modifier" }

absences_supprimer:
    path:   /supprimer
    defaults: { _controller: "EnseignantBundle:Absences:supprimer" }

absences_verifier:
    path:   /verifier
    defaults: { _controller: "EnseignantBundle:Absences:verifier" }
