sanctions_index:
    path:     /
    defaults: { _controller: "EnseignantBundle:Sanctions:index" }
    methods:  GET

sanctions_show:
    path:     /{id}/show
    defaults: { _controller: "EnseignantBundle:Sanctions:show" }
    methods:  GET

sanctions_new:
    path:     /new
    defaults: { _controller: "EnseignantBundle:Sanctions:new" }
    methods:  [GET, POST]

sanctions_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnseignantBundle:Sanctions:edit" }
    methods:  [GET, POST]

sanctions_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnseignantBundle:Sanctions:delete" }

sanctions_changeretat:
    path:   /{id}/changeretat
    defaults: { _controller: "EnseignantBundle:Sanctions:changeretat" }

sanctions_all:
    path:   /all/{id}
    defaults: { _controller: "EnseignantBundle:Sanctions:all" }

sanctions_sanctionseleve:
    path:   /sanctionseleve/{id}
    defaults: { _controller: "EnseignantBundle:Sanctions:sanctionseleve" }

sanctions_ajouter:
    path:   /ajouter
    defaults: { _controller: "EnseignantBundle:Sanctions:ajouter" }

sanctions_modifier:
    path:   /modifier
    defaults: { _controller: "EnseignantBundle:Sanctions:modifier" }

sanctions_supprimer:
    path:   /supprimer
    defaults: { _controller: "EnseignantBundle:Sanctions:supprimer" }





