<?php

namespace EdtechBundle\Repository;

/**
 * courseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class courseRepository extends \Doctrine\ORM\EntityRepository
{
}
