<?php

namespace EdtechBundle\Repository;

/**
 * coursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coursRepository extends \Doctrine\ORM\EntityRepository
{
}
