<?php

namespace EdtechBundle\Repository;

/**
 * scoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scoreRepository extends \Doctrine\ORM\EntityRepository
{
}
