<?php

namespace ScolariteBundle\Repository;
use EnseignantBundle\Repository;
use EnseignantBundle\Entity\Moyenne;
/**
 * CoeffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoeffRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCoeff($l,$cc)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT c.niveau
             FROM ScolariteBundle:Coeff p inner join  ScolariteBundle:Classe c with p.niveau= c.id
              WHERE c.niveau = :l and p.matiere =:m'
        )->setParameters([
            'l' => $l,
            'm' => $cc

        ]);

        return $products = $query->getResult();
    }


    public function MEleve($classe,$tr,$eleve)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT 
            ( sum((coeff.valeur* moyennes.moyenne))/ sum(coeff.valeur) )as moyG 
            from ScolariteBundle:Coeff  coeff inner join EnseignantBundle:Moyennes moyennes with coeff.matiere= moyennes.matiere
            and moyennes.trimestre= :m inner join ScolariteBundle:Classe c with c.niveau= coeff.niveau
              where moyennes.eleve= :ele  and c.niveau = :niv GROUP by moyennes.trimestre'
        )
            ->setParameters([
                'niv' => $classe,
                'm' => $tr,
                'ele' => $eleve



            ]);

        return $results = $query->getArrayResult();


    }

    public function TrouverB($eleve,$tr)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n from EnseignantBundle:Bulletin n where n.eleve = :el and n.trimestre = :tr '
        )
            ->setParameters([
                'el' => $eleve,
                'tr' => $tr


            ]);
        return $products = $query->getArrayResult();
    }

    public function TrouverE($eleve)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n from AppBundle:User n where n.id = :el '
        )
            ->setParameter('el', $eleve);
        return $products = $query->getResult();
    }

    public function TrouverMatiere($tr,$el)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n from EnseignantBundle:Moyennes n
            where n.trimestre = :idp and n.eleve = :el'
        )
            //->setParameter('idp', $tr);
            ->setParameters([
                'idp' => $tr,
                'el' => $el


            ]);
        return $products = $query->getResult();
    }

   

    public function TrouverNotes($tr,$el)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n from EnseignantBundle:Notes n where n.id_trimestre = :idp and n.eleve = :el GROUP BY n.matiere,n.type  '
        )
            //->setParameter('idp', $tr);
            ->setParameters([
                'idp' => $tr,
                'el' => $el


            ]);
        return $products = $query->getResult();
    }

  /*  public function ModifierB($tr,$el,$m)
    {
        $query = $this->getEntityManager()->createQuery(

            'update EnseignantBundle:Bulletin b set b.moyenne = :m where b.eleve = :el and b.trimestre = :tr  '
        )
            //->setParameter('idp', $tr);
            ->setParameters([
                'm' => $m,
                'el' => $el,
                'tr' => $tr


            ]);
        return $products = $query->getResult();
    }*/
}
