<?php

namespace ScolariteBundle\Repository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMat($l)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Matiere  p 
              WHERE p.nom = :l '
        )->setParameter('l', $l);

        return $products = $query->getResult();

    }
}
