<?php

namespace ScolariteBundle\Repository;

/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSalle($l)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Salle p 
              WHERE p.libelle = :l '
        )  ->setParameter('l', $l);

        return $products = $query->getResult();
    }


}
