<?php

namespace ScolariteBundle\Repository;
//use ScolariteBundle\Entity\Seance;
use Doctrine\ORM\EntityRepository;
/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{

    public function CheckSalleSeance($s, $deb,$j)
    {


        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Seance p
              WHERE p.salle = :s and p.hdeb = :deb  and p.jour= :j'
        )
            ->setParameters([
                's' => $s,
                'deb' => $deb,
                'j' => $j,
            ]);

        return $products = $query->getResult();
    }

    public function findSeanceC($id)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Seance p
              WHERE p.classe = :price'
        )->setParameter('price', $id);

        return $products = $query->getResult();
    }

    public function findSeanceE($id)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Seance p
              WHERE p.enseignant = :e'
        )->setParameter('e', $id);

        return $products = $query->getResult();
    }

    public function CheckNbS($classe, $ens, $j)
    {
        $query = $this->getEntityManager()->createQuery(


            'SELECT count(p.id) AS total, 
              sum(CASE WHEN p.enseignant = :e then 1 else 0 end) AS sp, 
              sum(CASE WHEN p.classe = :c then 1 else 0 end) AS sc FROM ScolariteBundle:Seance p where p.jour = :j'
        )->setParameters([
            'e' => $ens,
            'c' => $classe,
            'j' => $j,
        ]);

        return $results = $query->getArrayResult();

    }
}
