<?php

namespace ScolariteBundle\Repository;
//use ScolariteBundle\Entity\Seance;
use Doctrine\ORM\EntityRepository;
/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{
    public function TrouverEns($r)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n from AppBundle:User n where n.roles = :el '
        )
            ->setParameter('el', $r);
        return $products = $query->getResult();
    }

    public function TrouverElvM($r)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT u.id,u.nom,u.prenom,m.moyG from ScolariteBundle:Moyennesgenerales m 
            inner join AppBundle:User u with u.id = m.eleve
            inner join ScolariteBundle:Classe c with c.id= m.classe 
            WHERE c.libelle= :el ORDER BY m.moyG desc 
             
             '
        )
            ->setParameter('el', $r)
        ->setMaxResults(3);
        return $products = $query->getResult();
    }


    public function TrouverElv($r)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n from AppBundle:User n where n.roles = :el '
        )
            ->setParameter('el', $r);
        return $products = $query->getResult();
    }

    public function TrouverClasse($r)
    {
        $query = $this->getEntityManager()->createQuery(

            'select n.id,n.hdeb,n.hfin,n.jour,c.libelle as classe ,s.libelle as salle,u.nom,u.prenom,m.nom as matiere from ScolariteBundle:Seance n inner join ScolariteBundle:Classe c with 
              n.classe = c.id inner join ScolariteBundle:Salle s with s.id=n.salle 
              inner join AppBundle:User u with u.id=n.enseignant
              inner join ScolariteBundle:Matiere m with m.id=n.matiere
              where c.libelle = :el '
        )
            ->setParameter('el', $r);
        return $products = $query->getResult();
    }

    public function CheckSalleSeance($s, $deb,$j)
    {


        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Seance p
              WHERE p.salle = :s and p.hdeb = :deb  and p.jour= :j'
        )
            ->setParameters([
                's' => $s,
                'deb' => $deb,
                'j' => $j,
            ]);

        return $products = $query->getResult();
    }

    public function findSeanceC($id)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Seance p
              WHERE p.classe = :price'
        )->setParameter('price', $id);

        return $products = $query->getResult();
    }

    public function findSeanceE($id)
    {
        $query = $this->getEntityManager()->createQuery(

            'SELECT p
             FROM ScolariteBundle:Seance p
              WHERE p.enseignant = :e'
        )->setParameter('e', $id);

        return $products = $query->getResult();
    }

    public function CheckNbS($classe, $ens, $j)
    {
        $query = $this->getEntityManager()->createQuery(


            'SELECT count(p.id) AS total, 
              sum(CASE WHEN p.enseignant = :e then 1 else 0 end) AS sp, 
              sum(CASE WHEN p.classe = :c then 1 else 0 end) AS sc FROM ScolariteBundle:Seance p where p.jour = :j'
        )->setParameters([
            'e' => $ens,
            'c' => $classe,
            'j' => $j,
        ]);

        return $results = $query->getArrayResult();

    }
}
